### ISSUE TITLE
Validate filenames before calling Mantid

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scippneutron#151]
Calling `scn.load(filename='bogus.nxs')`with a non-existent file currently produces the following error
```
Traceback (most recent call last):
  File "/home/jl/Software/Miniconda3/envs/nscipp-2/lib/python3.7/site-packages/mantid/simpleapi.py", line 139, in Load
    algm.setProperty('Filename', filename)  # Must be set first
ValueError: Invalid value for property Filename (list of str lists) from string "bogus.nxs": When setting value of property "Slave": File "bogus.nxs" not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asd.py", line 4, in <module>
    da = scn.load(filename='bogus.nxs')
  File "/home/jl/Work/nscipp-2/install/scippneutron/mantid.py", line 839, in load
    with run_mantid_alg(mantid_alg, filename, **mantid_args) as loaded:
  File "/home/jl/Software/Miniconda3/envs/nscipp-2/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/jl/Work/nscipp-2/install/scippneutron/mantid.py", line 35, in run_mantid_alg
    ws = getattr(mantid, alg)(*args, **kwargs)
  File "/home/jl/Software/Miniconda3/envs/nscipp-2/lib/python3.7/site-packages/mantid/simpleapi.py", line 141, in Load
    msg = 'Problem setting "Filename" in {}-v{}: {}'.format(name, algm.name(), algm.version(),
NameError: name 'name' is not defined
```
which, apart from showing a bug in Mantid, is not particularly easy to understand. We can do better.

**Comment by OwenArnold** [comment]
Would checking the file exists and passing an appropriate error message directly rather than seeing Mantid's Algorithm Property errors be enough, or were you thinking of something else? FYI we cannot catch all errors - for example we cannot easily determine if the file extension is correct (valid) since it's the job of the Load Algorithm selector to determine what can/cannot be loaded.
