### ISSUE TITLE
`load` not working on OSX due broken Mantid 6.2 package?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scippneutron#227]
Setup `scippneutron` from fresh env as per install instructions, then:

```python
>>> import scippneutron as scn
>>> scn.load('abc')
Traceback (most recent call last):
  File "/Users/simonheybrock/opt/miniconda3/envs/scippneutron/lib/python3.9/site-packages/mantid/utils/_utils.py", line 37, in import_mantid_cext
    lib = import_module(modulename, package)
  File "/Users/simonheybrock/opt/miniconda3/envs/scippneutron/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: dlopen(/Users/simonheybrock/opt/miniconda3/envs/scippneutron/lib/python3.9/site-packages/mantid/kernel/_kernel.so, 2): Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /Users/simonheybrock/opt/miniconda3/envs/scippneutron/lib/python3.9/site-packages/mantid/kernel/_kernel.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/simonheybrock/opt/miniconda3/envs/scippneutron/lib/python3.9/site-packages/mantid/utils/_utils.py", line 41, in import_mantid_cext
    lib = import_module(modulename.lstrip('.'))
  File "/Users/simonheybrock/opt/miniconda3/envs/scippneutron/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_kernel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/simonheybrock/opt/miniconda3/envs/scippneutron/lib/python3.9/site-packages/scippneutron/mantid.py", line 863, in load
    _check_file_path(str(filename), mantid_alg)
  File "/Users/simonheybrock/opt/miniconda3/envs/scippneutron/lib/python3.9/site-packages/scippneutron/mantid.py", line 900, in _check_file_path
    from mantid.api import AlgorithmManager, FrameworkManager, FileProperty
  File "/Users/simonheybrock/opt/miniconda3/envs/scippneutron/lib/python3.9/site-packages/mantid/__init__.py", line 105, in <module>
    from mantid import kernel as _kernel  # noqa: F401, E402
  File "/Users/simonheybrock/opt/miniconda3/envs/scippneutron/lib/python3.9/site-packages/mantid/kernel/__init__.py", line 36, in <module>
    import_mantid_cext('._kernel', 'mantid.kernel', globals())
  File "/Users/simonheybrock/opt/miniconda3/envs/scippneutron/lib/python3.9/site-packages/mantid/utils/_utils.py", line 46, in import_mantid_cext
    raise ImportError(msg)
ImportError: First import of "._kernel" failed with "dlopen(/Users/simonheybrock/opt/miniconda3/envs/scippneutron/lib/python3.9/site-packages/mantid/kernel/_kernel.so, 2): Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /Users/simonheybrock/opt/miniconda3/envs/scippneutron/lib/python3.9/site-packages/mantid/kernel/_kernel.so
  Reason: image not found". Second import of "_kernel" failed with "No module named '_kernel'"
  ```

**Comment by SimonHeybrock** [comment]
As a workaround, change your env file (such as `scippneutron.yml`) to use

```
  - scipp::mantid-framework=6.0
```

**Comment by SimonHeybrock** [comment]
Closing, since we are now using the official Mantid conda package (`mantid::mantid`). `scipp::mantid-framework` is not relevant any more.
