### ISSUE TITLE
Update mantid to 6.8

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scippneutron#462]
There seems to have been some change to `simpleapi` in the the latest version of Mantid. E.g., I'm getting this error
```
tests/mantid_test.py:189 (TestMantidConversion.test_from_mantid_LoadEmptyInstrument)
self = <tests.mantid_test.TestMantidConversion testMethod=test_from_mantid_LoadEmptyInstrument>

    def test_from_mantid_LoadEmptyInstrument(self):
        import mantid.simpleapi as mantid
    
        ws = mantid.LoadEmptyInstrument(InstrumentName='PG3')
>       scn.from_mantid(ws)

tests/mantid_test.py:194: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/scippneutron/mantid.py:1068: in from_mantid
    workspace, monitor_ws = mantid.ExtractMonitors(workspace)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (Workspace2D
Title: 
Histograms: 43121
Bins: 1
Histogram
X axis:  / 
Y axis: 
Distribution: False
Instrument: POWGEN (...ware/mambaforge/envs/scipp-upgrade/instrument/POWGEN_Parameters.xml
Run start: not available
Run end:  not available
,)
kwargs = {}

    def fake_function(*args, **kwargs):
>       raise RuntimeError(
            "Mantid import error. The mock simple API functions have not been replaced!"
            " This is an error in the core setup logic of the mantid module, "
            "please contact the development team."
        )
E       RuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.

/home/jl/Software/mambaforge/envs/scipp-upgrade/lib/python3.10/site-packages/mantid/simpleapi.py:1206: RuntimeError
```

Are we doing something wrong or is this indeed an internal error in Mantid?

**Comment by jl-wynen** [comment]
This was triggered by a deprecation warning within mantid:
```
Python-[Warning] Failed to load plugin /home/jl/Software/mambaforge/envs/scipp-upgrade/plugins/python/functions/Examples/ExamplePeakFunction.py.
Error: Traceback (most recent call last):
  File "/home/jl/Software/mambaforge/envs/scipp-upgrade/lib/python3.10/site-packages/mantid/kernel/plugins.py", line 188, in load_from_file
    name, module = load_plugin(filepath)
  File "/home/jl/Software/mambaforge/envs/scipp-upgrade/lib/python3.10/site-packages/mantid/kernel/plugins.py", line 209, in load_plugin
    module = loader.run()
  File "/home/jl/Software/mambaforge/envs/scipp-upgrade/lib/python3.10/site-packages/mantid/kernel/plugins.py", line 48, in run
    return SourceFileLoader(name, pathname).load_module()
  File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1063, in load_module
  File "<frozen importlib._bootstrap_external>", line 888, in load_module
  File "<frozen importlib._bootstrap>", line 283, in _load_module_shim
DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instea
```

I suppressed the warning as part of #461
